---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords: whats new, enhancements, new features 
summary: NetApp会定期更新Astra Control REST API、为您提供新功能、增强功能和错误修复。 
---
= Astra Control REST API 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp会定期更新Astra Control REST API、为您提供新功能、增强功能和错误修复。



== 2023年4月25日(23.04)

此版本包含对REST API的选择性更新。



=== 选择性还原操作

您可以在还原操作期间有选择地包括或排除应用程序资源。可以使用基于特定命名空间、名称、标签或GroupVersion Kind值的筛选器规则来完成此操作。



=== 支持纯数据应用程序

对管理应用程序的支持已扩展到纯数据应用程序。



== 2023年1月17日(23.01)

此版本对REST API进行了少量更新。



=== 通过筛选器增强了执行挂钩功能

现在、在使用执行挂钩时、您可以添加筛选器来控制挂钩要匹配的容器。如果为单个执行钩创建多个筛选器、则这些筛选器将与逻辑运算符和运算符结合使用。每个执行挂机最多可以定义10个活动筛选器。



== 2022年11月22日(22.11)

此版本包括对REST API的扩展和更新、以及增强的命名空间和LDAP支持。



=== 新增和增强的 Astra 资源

添加了四种新的资源类型：* apiResource*、* ldapGroup*、* LDAP用户*和*任务*。此外、还对多个现有资源和端点进行了改进。



=== 监控对长期运行任务的支持

新的任务端点可用于访问受管任务资源、并可用于显示内部长时间运行的任务的状态。



=== 增强的命名空间使用情形

增加了对跨多个命名空间的应用程序以及与符合命名空间要求的资源关联的集群资源的支持。



=== 扩展了云订阅

现在、可以为每个云提供商添加多个帐户订阅。



=== 其他工作流

添加了说明Astra Control REST API的其他工作流。请参见 link:../workflows_infra/workflows_infra_before.html["基础架构工作流"] 和 link:../workflows/workflows_before.html["管理工作流"] 有关详细信息 ...

.相关信息
* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra 控制中心：新增功能"^]




== 2022年8月10日(22.08)

此版本包括对 REST API 的扩展和更新，以及增强的安全性和管理功能。



=== 新增和增强的 Astra 资源

添加了三种新的资源类型：*证书*、*组*和*应用镜像*。此外、还更新了多个现有资源的版本。



=== LDAP 身份验证

您可以选择将Astra控制中心配置为与LDAP服务器集成、以便对选定的Astra用户进行身份验证。请参见 link:../workflows_infra/ldap_prepare.html["LDAP 配置"] 有关详细信息 ...



=== 增强的执行钩

Astra Control 21.12版增加了对执行挂钩的支持。除了现有的预快照和后快照执行挂钩之外、您现在还可以在22.08版本中配置以下类型的执行挂钩：

* 预备份
* 备份后
* 还原后


Astra Control现在还允许将同一个脚本用于多个执行挂钩。



=== 使用SnapMirror进行应用程序复制

现在、您可以使用NetApp SnapMirror技术在集群之间复制数据和应用程序更改。此增强功能可用于提高业务连续性和恢复能力。

.相关信息
* https://docs.netapp.com/us-en/astra-control-center-2208/release-notes/whats-new.html["Astra控制中心22.08：新增功能"^]




== 2022 年 4 月 26 日（ 22.04 ）

此版本包括对 REST API 的扩展和更新，以及增强的安全性和管理功能。



=== 新增和增强的 Astra 资源

添加了两种新的资源类型： * 软件包 * 和 * 升级 * 。此外，已升级多个现有资源的版本。



=== 具有命名空间粒度的增强型 RBAC

将角色绑定到关联用户时，您可以限制用户有权访问的命名空间。请参见 * 角色绑定 API" 参考和 link:../additional/rbac.html["RBAC 安全性"] 有关详细信息 ...



=== 删除存储分段

您可以在不再需要某个存储分段或此存储分段无法正常运行时将其删除。



=== 支持 Cloud Volumes ONTAP

现在支持将 Cloud Volumes ONTAP 用作存储后端。



=== 其他产品增强功能

这两种 Astra Control 产品实施还有几项额外的增强功能，包括：

* Astra 控制中心的通用传入
* AKS 中的专用集群
* 支持 Kubernetes 1.22
* 支持 VMware Tanzu 产品组合


请参见 Astra 控制中心和 Astra 控制服务文档站点上的 * 新增功能 * 页面。

.相关信息
* https://docs.netapp.com/us-en/astra-control-center-2204/release-notes/whats-new.html["Astra控制中心22.04：新增功能"^]




== 2021 年 12 月 14 日（ 21.12 ）

此版本扩展了 REST API ，并对文档结构进行了更改，以便在未来的版本更新中更好地支持 Astra Control 的发展。



=== 每个版本的 Astra Control 都有单独的 Astra Automation 文档

每个版本的 Astra Control 都包含一个独特的 REST API ，该 API 已根据特定版本的功能进行了增强和定制。每个版本的 Astra Control REST API 的文档以及相关的 GitHub 内容存储库现在均可从其自己的专用网站上获得。主文档站点 https://docs.netapp.com/us-en/astra-automation/["Astra Control Automation"^] 始终包含最新版本的文档。请参见 link:../aa-earlier-versions.html["早期版本的 Astra Control Automation 文档"] 有关先前版本的信息。



=== 扩展 REST 资源类型

REST 资源类型的数量不断增加，重点是执行挂钩和存储后端。新资源包括：帐户，执行钩，钩源，执行钩覆盖，集群节点， 受管存储后端，命名空间，存储设备和存储节点。请参见 link:../endpoints/resources.html["Resources"] 有关详细信息 ...



=== NetApp Astra Control Python SDK

NetApp Astra Control Python SDK 是一个开源软件包，可以更轻松地为您的 Astra Control 环境开发自动化代码。其核心是 Astra SDK ，其中包含一组类，用于抽象化 REST API 调用的复杂性。此外，还提供了一个工具包脚本，用于通过包装和抽象化 Python 类来执行特定管理任务。请参见 link:../python/astra_toolkits.html["NetApp Astra Control Python SDK"] 有关详细信息 ...

.相关信息
* https://docs.netapp.com/us-en/astra-control-center-2112/release-notes/whats-new.html["Astra控制中心21.12：新增功能"^]




== 2021 年 8 月 5 日（ 21.08 ）

此版本引入了新的 Astra 部署模式，并对 REST API 进行了重大扩展。



=== Astra 控制中心部署模式

除了作为公有云服务提供的现有 Astra 控制服务之外，此版本还包括 Astra 控制中心内部部署模式。您可以在站点上安装 Astra 控制中心来管理本地 Kubernetes 环境。两种 Astra Control 部署模式共享同一个 REST API ，但文档中会根据需要指出一些细微的差异。



=== 扩展 REST 资源类型

通过 Astra Control REST API 访问的资源数量已大幅增加，许多新资源为内部 Astra Control Center 产品奠定了基础。新资源包括： ASUP ，授权，功能，许可证，设置， 订阅，存储分段，云，集群，受管集群， 存储后端和存储类。请参见 link:../endpoints/resources.html["Resources"] 有关详细信息 ...



=== 支持 Astra 部署的其他端点

除了扩展的 REST 资源之外，还有其他几个新的 API 端点可用于支持 Astra Control 部署。

支持 OpenAPI:: 通过 OpenAPI 端点可以访问当前的 OpenAPI JSON 文档和其他相关资源。
支持 OpenMetrics:: 通过 OpenMetrics 资源，您可以通过 OpenMetrics 端点访问帐户指标。


.相关信息
* https://docs.netapp.com/us-en/astra-control-center-2108/release-notes/whats-new.html["Astra Control Center 21.08：新增功能"^]




== 2021 年 4 月 15 日（ 21.04 ）

此版本包含以下新增功能和增强功能：



=== 引入 REST API

Astra Control REST API 可与 Astra Control Service 产品配合使用。它是基于 REST 技术和当前最佳实践创建的。API 为 Astra 部署的自动化奠定了基础，并具有以下功能和优势。

Resources:: 有 14 种可用的 REST 资源类型。
API 令牌访问:: REST API 的访问通过 API 访问令牌提供，您可以在 Astra Web 用户界面上生成此令牌。通过 API 令牌，可以安全地访问 API 。
支持收集:: 有一组丰富的查询参数，可用于访问资源集合。支持的部分操作包括筛选，排序和分页。

