---
sidebar: sidebar 
permalink: workflows_infra/wf_create_user.html 
keywords:  
summary: 您可以使用特定凭据和预定义角色创建用户。您也可以选择限制用户对特定命名空间的访问。 
---
= 创建用户
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用特定凭据和预定义角色创建用户。您也可以选择限制用户对特定命名空间的访问。



== 第1步：选择用户名

执行工作流 link:../workflows_infra/wf_list_users.html["列出用户"] 并选择当前未使用的可用名称。



== 第2步：创建用户

执行以下REST API调用以创建用户。成功完成调用后、新用户将无法使用。

.HTTP方法和端点
此REST API调用使用以下方法和端点。

[cols="25,75"]
|===
| HTTP 方法 | 路径 


| 发布 | /accouns/｛account_id｝/core/v1/users 
|===
.curl 示例
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/core/v1/users" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON 输入示例
[source, json]
----
{
  "type" :  "application/astra-user",
  "version" : "1.1",
  "firstName" : "John",
  "lastName" : "West",
  "email" : "jwest@example.com"
}
----
.JSON 输出示例
[listing]
----
{
    "metadata": {
        "creationTimestamp": "2022-11-20T17:23:15Z",
        "modificationTimestamp": "2022-11-20T17:23:15Z",
        "createdBy": "a20e91f3-2c49-443b-b240-615d940ec5f3",
        "labels": []
    },
    "type": "application/astra-user",
    "version": "1.2",
    "id": "d07dac0a-a328-4840-a216-12de16bbd484",
    "authProvider": "local",
    "authID": "jwest@example.com",
    "firstName": "John",
    "lastName": "West",
    "companyName": "",
    "email": "jwest@example.com",
    "postalAddress": {
        "addressCountry": "",
        "addressLocality": "",
        "addressRegion": "",
        "streetAddress1": "",
        "streetAddress2": "",
        "postalCode": ""
    },
    "state": "active",
    "sendWelcomeEmail": "false",
    "isEnabled": "true",
    "isInviteAccepted": "true",
    "enableTimestamp": "2022-11-20T17:23:15Z",
    "lastActTimestamp": ""
}
----


== 第3步：(可选)选择允许的名称空格

执行工作流 link:../workflows/wf_list_namespaces.html["列出命名空间"] 并选择要限制访问的命名空间。



== 第4步：将用户绑定到角色

执行以下REST API调用以将用户绑定到角色。以下示例对命名空间访问没有任何限制。请参见 link:../additional/rbac.html#enhanced-rbac-with-namespace-granularity["具有命名空间粒度的增强型 RBAC"] 有关详细信息 ...

.HTTP方法和端点
此REST API调用使用以下方法和端点。

[cols="25,75"]
|===
| HTTP 方法 | 路径 


| 发布 | /accouns/｛account_id｝/core/v1/roleBindings 
|===
.curl 示例
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/core/v1/roleBindings" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON 输入示例
[source, json]
----
{
  "type" :  "application/astra-roleBinding",
  "version" : "1.1",
  "userID" : "d07dac0a-a328-4840-a216-12de16bbd484",
  "accountID" : "29e1f39f-2bf4-44ba-a191-5b84ef414c95",
  "role" : "viewer",
  "roleConstraints": [ "*" ]
}
----


== 第5步：创建凭据

执行以下REST API调用以创建凭据并将其与用户关联。此示例使用作为base64值提供的密码。。 `name` 属性应包含上一步返回的用户的ID。输入属性 `change` 还必须在base64中进行编码、并确定用户是否必须在首次登录时更改其密码 (`true` 或 `false`）。


NOTE: 只有使用本地身份验证部署Astra控制中心时、才需要执行此步骤。使用LDAP部署Astra控制中心或部署Astra控制服务时不需要此功能。

.HTTP方法和端点
此REST API调用使用以下方法和端点。

[cols="25,75"]
|===
| HTTP 方法 | 路径 


| 发布 | /accouns/｛account_id｝/core/v1/credentials 
|===
.curl 示例
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/core/v1/credentials" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON 输入示例
[source, json]
----
{
  "type" :  "application/astra-credential",
  "version" : "1.1",
  "name" : "d07dac0a-a328-4840-a216-12de16bbd484",
  "keyType" : "passwordHash",
  "keyStore" : {
      "cleartext" : "TmV0QXBwMTIz",
      "change" : "ZmFsc2U="
  },
  "valid" : "true"
}
----