---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-executionhookoverrides.html 
summary: 列出应用程序的执行挂钩覆盖资源 
---
= 列出应用程序的执行挂钩覆盖资源
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHookOverrides`#

返回集合中所有匹配资源的 JSON 数组。如果在请求中指定了单个字段，则项目 JSON 数组将包含按指定顺序为每个匹配资源请求的字段。


CAUTION: 此操作已弃用。



[[parameters]]
== 参数

[cols="5*"]
|===
| 名称 | Type | 在 | Required | Description 


| account_id | string | path | True  a| 
包含帐户资源的 ID

* 示例：{{.Account}}




| app_id | string | path | True  a| 
包含应用程序资源的 ID



| 包括 | string | 查询 | False  a| 
指示列出集合时应返回哪些字段。

URL 示例："include=id"、"include=id,name"

OpenAPI 示例："id"



| limit | string | 查询 | False  a| 
指示列出集合时要返回的最大资源数。

URL 示例："limit=2"

OpenAPI 示例："2"



| 筛选器 | string | 查询 | False  a| 
指示在列出集合时应匹配哪些字段以返回资源。

支持的运算符有：

* eq - 相等
* lt/gt - 小于/大于
* lte/gte - 小于或等于/大于或等于


URL 示例："filter=field%20eq%20%27value%27"

OpenAPI 示例："field eq 'value'"

|===


[[response]]
== 响应

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| 个项 | 数组[任意以下之一：link:#executionHookOverride_1_0_get_response_body["executionHookOverride_1.0_get_response_body"]，数组[]] | True  a| 



| 元数据 | link:#type_astra_metadata_list["type_astra_metadata_list"] | True  a| 

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverrides",
  "version": "1.0",
  "items": [
    {
      "type": "application/astra-executionHookOverride",
      "version": "1.0",
      "id": "36d06222-bd0c-4897-89c2-c16dd9265e12",
      "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
      "enabled": "false",
      "appID": "4b43c2f7-bffa-4f60-b595-d98a05b64bc9",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "863feb92-8619-4298-b222-c48a886024f8"
      }
    },
    {
      "type": "application/astra-executionHookOverride",
      "version": "1.0",
      "id": "f8d1ce66-6c0e-4d3a-96c5-a5e76669442d",
      "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
      "enabled": "false",
      "appID": "36b076ae-b7c4-4e96-a323-ed167ede74ba",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "863feb92-8619-4298-b222-c48a886024f8"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== 响应

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== 响应

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 数组[link:#invalidParams["invalidParams"]] | False  a| 
无效查询参数列表

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== 响应

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== 错误

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.错误响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== 定义

.查看定义
[%collapsible]
====
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
类型 Astra 标签

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 



| value | string | True  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

与资源关联的客户端和服务指定的元数据。定义的值为：

* 符合 Astra 元数据架构如果在创建时未指定，则将创建没有标签的元数据对象。如果在更新时未指定，则元数据对象的标签、creationTimestamp 和 createdBy 将保留而不进行修改。


[cols="4*"]
|===
| 名称 | Type | Required | Description 


| labels | 数组[link:#type_astra_label["类型 Astra 标签"]] | False  a| 



| creationTimestamp | string | False  a| 



| modificationTimestamp | string | False  a| 



| 已创建 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[[executionHookOverride_1_0_get_response_body]]
[role="api-collapsible-fifth-title"]
executionHookOverride_1.0_get_response_body

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 
资源的媒体类型。定义的值为：

* "application/astra-executionHookOverride"




| version | string | True  a| 
资源的版本。定义的值为：

* "1.0"




| id | string | True  a| 
资源的全局唯一标识符。定义的值为：

* 符合 UUIDv4 架构




| executionHookID | string | True  a| 
包含执行挂钩 ID 的 JSON 字符串。定义的值为：

* 符合 Astra 标识符架构 仅允许 hookType 值为 "netapp" 的执行挂钩资源的 executionHookID。




| 启用 | string | True  a| 
指示是否为指定应用程序启用了执行挂钩的 JSON 字符串。定义的值为：

* "true" - 执行挂钩已启用，将按指定顺序运行
* "false" - 执行挂钩已禁用，无法运行




| appID | string | True  a| 
包含重写链接的应用程序的关联 ID 的 JSON 字符串。定义的值是：

* 符合 Astra 标识符架构




| 元数据 | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
与资源关联的客户端和服务指定的元数据。定义的值为：

* 符合 Astra 元数据架构如果在创建时未指定，则将创建没有标签的元数据对象。如果在更新时未指定，则元数据对象的标签、creationTimestamp 和 createdBy 将保留而不进行修改。


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| 继续 | string | False  a| 



| count | 数字 | False  a| 



| labels | 数组[link:#type_astra_label["类型 Astra 标签"]] | False  a| 



| creationTimestamp | string | False  a| 



| modificationTimestamp | string | False  a| 



| 已创建 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 
无效查询参数的名称



| 原因 | string | True  a| 
查询参数无效的原因

|===
====