---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-executionhooks-.html 
summary: 检索应用的执行挂钩 
---
= 检索应用的执行挂钩
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks/{executionHook_id}`#

在 JSON 响应正文中返回已存储的 Execution Hook API 资源。还会根据当前的 matchingCriteria 和已定义的应用填充 matchingContainers 及 matchingImages。



[[parameters]]
== 参数

[cols="5*"]
|===
| 名称 | Type | 在 | Required | Description 


| account_id | string | path | True  a| 
包含帐户资源的 ID

* 示例：{{.Account}}




| app_id | string | path | True  a| 
包含应用程序资源的 ID



| executionHook_id | string | path | True  a| 
要列出的 executionHook 集合的 ID

|===


[[response]]
== 响应

[source]
----
Status: 200, Returns the stored Execution Hook API resource in the JSON response body. Also populates matchingContainers and matchingImages based on the current matchingCriteria and the defined app.
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 
资源的媒体类型。定义的值为：

* "application/astra-executionHook"




| version | string | True  a| 
资源的版本。定义的值为：

* "1.0"
* "1.1"
* "1.2"
* "1.3"




| id | string | True  a| 
资源的全局唯一标识符。定义的值为：

* 符合 UUIDv4 架构




| name | string | True  a| 
包含用户指定的资源名称的 JSON 字符串。定义的值是：

* 最小长度：1
* 最大长度：63 名称在所有执行挂钩资源中必须是唯一的。




| hookType | string | True  a| 
定义挂钩类型的 JSON 字符串。定义的值为：

* "netapp" - NetApp 提供执行挂钩。
* "custom" - 与特定应用 ID 相关联。使用 hookType "netapp" 的执行挂钩资源是只读的。




| matchingCriteria | 数组[link:#matchingCriteria["matchingCriteria"]] | True  a| 
描述执行挂钩匹配条件的 JSON 对象的 JSON 数组。当指定多个 matchingCriteria 时，逻辑 AND 应用于条件。定义的值是：

* 最小项目数：0
* 最多项目数：10




| matchingContainers | 数组[link:#matchingContainers["matchingContainers"]] | False  a| 
与定义的应用程序中配置的匹配条件匹配的每个容器的 JSON 对象的 JSON 数组。



| matchingImages | 数组[string] | False  a| 
匹配容器镜像的 JSON 字符串的 JSON 数组。定义的值是：

* 最小项目数：0
* 最大项目数：4095
* 最小长度：1
* 最大长度：255




| 操作 | string | True  a| 
JSON 字符串，指示在满足匹配条件的情况下执行挂钩将运行的操作。定义的值为：

* “快照”
* “备份”
* “还原”
* “故障转移”




| 阶段 | string | True  a| 
JSON 字符串，指示操作期间将执行挂钩的阶段。定义的值为：

* "pre" - 执行挂钩将在指定操作之前运行。
* "post" - 执行挂钩将在指定操作后运行。操作 "snapshot" 的值为 "pre" 和 "post"。操作 "backup" 的值为 "pre" 和 "post"。操作 "restore" 的值为 "post"。操作 "failover" 的值为 "post"。




| hookSourceID | string | True  a| 
包含通过此执行挂钩运行的挂钩源 ID 的 JSON 字符串。定义的值为：

* 符合 Astra 标识符架构




| 参数 | 数组[string] | False  a| 
用于源参数的 JSON 字符串的 JSON 数组。定义的值为：

* 最小项目数：0
* 最多项目数：16
* 最小长度：0
* 最大长度：127




| appID | string | False  a| 
包含此挂钩链接到的应用程序的关联 ID 的 JSON 字符串。实质上，其他匹配条件（如果设置）。定义的值是：

* 符合 Astra 标识符架构




| 启用 | string | True  a| 
指示是否启用了执行挂钩的 JSON 字符串。定义的值为：

* "true" - 已启用执行挂钩并将按指定方式运行。
* "false" - 执行挂钩被禁用，永远不会运行。默认值为 "true"。




| description | string | False  a| 
包含用户指定的钩子源描述的 JSON 字符串。定义的值是：

* 最小长度：0
* 最大长度：511




| 元数据 | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
与资源关联的客户端和服务指定的元数据。定义的值为：

* 符合 Astra 元数据架构如果在创建时未指定，则将创建没有标签的元数据对象。如果在更新时未指定，则元数据对象的标签、creationTimestamp 和 createdBy 将保留而不进行修改。


|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "id": "5f7e2e31-280d-5984-a28b-2d19ab5b77c0",
  "name": "Payroll",
  "hookType": "custom",
  "matchingCriteria": [
    {
      "type": "podLabel",
      "value": "^env=production$"
    },
    {
      "type": "containerName",
      "value": "^payroll-master"
    }
  ],
  "matchingImages": [
    "docker.io/bitnami/payroll:3.7.8",
    "docker.io/bitnami/payroll:4.1.2"
  ],
  "matchingContainers": [
    {
      "namespaceName": "payroll-east",
      "podName": "payroll-release3-7",
      "podLabels": [
        {
          "name": "env",
          "value": "production"
        },
        {
          "name": "app.kubernetes.io/managed-by",
          "value": "Helm"
        }
      ],
      "containerName": "payroll-master-0",
      "containerImage": "docker.io/bitnami/payroll:3.7.8"
    },
    {
      "namespaceName": "payroll-east",
      "podName": "payroll-release3-7",
      "podLabels": [
        {
          "name": "env",
          "value": "production"
        },
        {
          "name": "app.kubernetes.io/managed-by",
          "value": "Helm"
        }
      ],
      "containerName": "payroll-master-1",
      "containerImage": "docker.io/bitnami/payroll:3.7.8"
    }
  ],
  "action": "snapshot",
  "stage": "pre",
  "hookSourceID": "50e89023-ba84-435d-bb47-1833f4c250ff",
  "arguments": [
    "freeze"
  ],
  "appID": "7be5ae7c-151d-4230-ac39-ac1d0b33c2a9",
  "enabled": "true",
  "description": "Payroll production hook",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== 响应

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== 响应

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 



| invalidParams | 数组[link:#invalidParams["invalidParams"]] | False  a| 
无效查询参数列表

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== 响应

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== 错误

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.错误响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== 定义

.查看定义
[%collapsible]
====
[[matchingCriteria]]
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 
标识匹配条件类型的 JSON 字符串。



| value | string | True  a| 
包含用于匹配给定匹配类型的正则表达式的 JSON 字符串。正则表达式语法： https://github.com/google/re2/wiki/Syntax[]

|===
[[type_k8s_label]]
[role="api-collapsible-fifth-title"]
type_k8s_label

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 



| value | string | True  a| 

|===
[[matchingContainers]]
[role="api-collapsible-fifth-title"]
matchingContainers

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| podName | string | False  a| 
匹配容器的 pod 名称的 JSON 字符串。



| podLabels | 数组[link:#type_k8s_label["type_k8s_label"]] | False  a| 
匹配容器 Pod 标签的标签对象的 JSON 数组。



| containerImage | string | False  a| 
匹配容器镜像的 JSON 字符串。



| containerName | string | False  a| 
匹配容器名称的 JSON 字符串。



| namespaceName | string | False  a| 
匹配容器的 Pod 命名空间名称的 JSON 字符串。

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
类型 Astra 标签

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 



| value | string | True  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

与资源关联的客户端和服务指定的元数据。定义的值为：

* 符合 Astra 元数据架构如果在创建时未指定，则将创建没有标签的元数据对象。如果在更新时未指定，则元数据对象的标签、creationTimestamp 和 createdBy 将保留而不进行修改。


[cols="4*"]
|===
| 名称 | Type | Required | Description 


| labels | 数组[link:#type_astra_label["类型 Astra 标签"]] | False  a| 



| creationTimestamp | string | False  a| 



| modificationTimestamp | string | False  a| 



| 已创建 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 
无效查询参数的名称



| 原因 | string | True  a| 
查询参数无效的原因

|===
====