---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-users.html 
summary: 创建新用户 
---
= 创建新用户
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users`#

指示要创建的 User API 资源的所需值。



== 参数

[cols="5*"]
|===
| 名称 | Type | 在 | Required | Description 


| account_id | string | path | True  a| 
包含帐户资源的 ID

* 示例：{{.Account}}


|===


== 请求正文

指示要创建的 User API 资源的所需值。

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 
资源的媒体类型。定义的值为：

* "application/astra-user"




| version | string | True  a| 
资源的版本。定义的值为：

* "1.0"
* "1.1"
* "1.2"




| authID | string | False  a| 
包含与外部标识提供程序关联的标识符的 JSON 字符串。此字符串的内容取决于指定的 authProvider。对于 "authProvider" 为 "local" 的用户，"authID" 设置为 "email" 的值。对于 "authProvider" 为 "ldap" 的用户，"authID" 设置为其来自 LDAP 服务器的可分辨名称 (DN)。



| authProvider | string | False  a| 
表示 idAuth 标识符上下文的 JSON 字符串。定义的值为：

* "cloud-central" - 用户身份验证来自 NetApp Cloud Central 服务
* "local" - 用户身份验证来自本地用户/密码存储
* "ldap" - 用户身份验证来自外部 LDAP 服务器。在 Astra Control Center 中，所有用户都必须具有 "local" 或 "ldap" 值。如果未指定值，则选择默认值 "local"。在 Astra Control Service 中，不支持将 "authProvider" 设为 "local" 或 "ldap"。如果未指定值，则默认为 "cloud-central"。




| firstName | string | False  a| 
包含用户指定的长格式名字的 JSON 字符串。定义的值为：

* 最小长度：0
* 最大长度：63
* 此字符串经过内部验证，可防止 XSS、Unicode、目录遍历和 SQL 注入攻击




| lastName | string | False  a| 
包含用户指定的长格式姓氏的 JSON 字符串。定义的值为：

* 最小长度：0
* 最大长度：63
* 此字符串经过内部验证，可防止 XSS、Unicode、目录遍历和 SQL 注入攻击




| companyName | string | False  a| 
包含与用户关联的公司名称的 JSON 字符串。如果此密钥不存在，则表示未提供公司名称。定义的值为：

* 最小长度：1
* 最大长度：63
* 此字符串经过内部验证，可防止 XSS、Unicode、目录遍历和 SQL 注入攻击




| 电子邮件 | string | True  a| 
包含用户指定的电子邮件地址的 JSON 字符串。



| 电话 | string | False  a| 
包含用户电话号码的 JSON 字符串。如果此密钥不存在，则表示未提供电话号码。



| postalAddress | link:#postalAddress["postalAddress"] | False  a| 
JSON 对象包含指定地址的字段集合。如果此 key 不存在，则表示未提供地址。如果此 key 存在，则所有六个包含的字段都将存在。如果用户未提供任何内容，则字符串将为空。



| sendWelcomeEmail | string | False  a| 
表示是否在验证后发送欢迎电子邮件的 JSON 字符串。如果在创建时未指定，则 ACS 的值将设置为 "true"，Astra Control Center 的值将设置为 "false"。定义的值为：

* "true" - 将发送一封欢迎电子邮件；创建时为默认值
* "false" - 不会发送欢迎电子邮件。对于 "authProvider" 为 "local" 或 "ldap" 的用户，此值将被忽略并设置为 "false"。




| 元数据 | link:#type_astra_metadata_update["type_astra_metadata_update"] | False  a| 
与资源关联的客户端和服务指定的元数据。定义的值为：

* 符合 Astra 元数据架构如果在创建时未指定，则将创建没有标签的元数据对象。如果在更新时未指定，则元数据对象的标签、creationTimestamp 和 createdBy 将保留而不进行修改。


|===
.请求示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-user",
  "version": "1.2",
  "firstName": "John",
  "lastName": "Doe",
  "email": "jdoe@example.com"
}
----
====


== 响应

[source]
----
Status: 201, Returns the newly created user resource in the JSON response body.
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 
资源的媒体类型。定义的值为：

* "application/astra-user"




| version | string | True  a| 
资源的版本。定义的值为：

* "1.0"
* "1.1"
* "1.2"




| id | string | True  a| 
资源的全局唯一标识符。定义的值为：

* 符合 UUIDv4 架构




| 状态 | string | True  a| 
包含指示用户操作状态的值的 JSON 字符串。定义的值为：

* "pending" - 正在创建用户帐户。用户只能读取和修改用户资源（默认值）。
* 此状态对于 "authProvider" 为 "local" 的用户无效
* "active" - 用户帐户是可操作的（如果帐户设置"isEnabled"为"true"，则用户可以登录）。
* 这是 "authProvider" 为 "local" 的用户的默认值
* "suspended" - 用户帐户已暂停（无论帐户 "isEnabled" 设置如何，用户都无法登录）。




| isEnabled | string | True  a| 
指示是否允许用户登录的 JSON 字符串。定义的值为：

* "true" - 允许用户登录；创建时为默认值。
* "false" - 不允许此用户登录。




| authID | string | False  a| 
包含与外部标识提供程序关联的标识符的 JSON 字符串。此字符串的内容取决于指定的 authProvider。对于 "authProvider" 为 "local" 的用户，"authID" 设置为 "email" 的值。对于 "authProvider" 为 "ldap" 的用户，"authID" 设置为其来自 LDAP 服务器的可分辨名称 (DN)。



| authProvider | string | False  a| 
表示 idAuth 标识符上下文的 JSON 字符串。定义的值为：

* "cloud-central" - 用户身份验证来自 NetApp Cloud Central 服务
* "local" - 用户身份验证来自本地用户/密码存储
* "ldap" - 用户身份验证来自外部 LDAP 服务器。在 Astra Control Center 中，所有用户都必须具有 "local" 或 "ldap" 值。如果未指定值，则选择默认值 "local"。在 Astra Control Service 中，不支持将 "authProvider" 设为 "local" 或 "ldap"。如果未指定值，则默认为 "cloud-central"。




| firstName | string | True  a| 
包含用户指定的长格式名字的 JSON 字符串。定义的值为：

* 最小长度：0
* 最大长度：63
* 此字符串经过内部验证，可防止 XSS、Unicode、目录遍历和 SQL 注入攻击




| lastName | string | True  a| 
包含用户指定的长格式姓氏的 JSON 字符串。定义的值为：

* 最小长度：0
* 最大长度：63
* 此字符串经过内部验证，可防止 XSS、Unicode、目录遍历和 SQL 注入攻击




| companyName | string | False  a| 
包含与用户关联的公司名称的 JSON 字符串。如果此密钥不存在，则表示未提供公司名称。定义的值为：

* 最小长度：1
* 最大长度：63
* 此字符串经过内部验证，可防止 XSS、Unicode、目录遍历和 SQL 注入攻击




| 电子邮件 | string | True  a| 
包含用户指定的电子邮件地址的 JSON 字符串。



| 电话 | string | False  a| 
包含用户电话号码的 JSON 字符串。如果此密钥不存在，则表示未提供电话号码。



| postalAddress | link:#postalAddress["postalAddress"] | False  a| 
JSON 对象包含指定地址的字段集合。如果此 key 不存在，则表示未提供地址。如果此 key 存在，则所有六个包含的字段都将存在。如果用户未提供任何内容，则字符串将为空。



| sendWelcomeEmail | string | True  a| 
表示是否在验证后发送欢迎电子邮件的 JSON 字符串。如果在创建时未指定，则 ACS 的值将设置为 "true"，Astra Control Center 的值将设置为 "false"。定义的值为：

* "true" - 将发送一封欢迎电子邮件；创建时为默认值
* "false" - 不会发送欢迎电子邮件。对于 "authProvider" 为 "local" 或 "ldap" 的用户，此值将被忽略并设置为 "false"。




| enableTimestamp | string | False  a| 
包含 ISO-8601 格式时间戳的 JSON 字符串，指示上次启用用户的时间。已定义的值为：

* 符合 ISO-8601 日期时间方案




| lastActTimestamp | string | False  a| 
包含 ISO-8601 格式时间戳的 JSON 字符串，指示上次代表此用户调用身份 API 的时间。（注：这是昂贵的。）定义的值为：

* 符合 ISO-8601 日期时间方案




| 元数据 | link:#type_astra_metadata_update["type_astra_metadata_update"] | True  a| 
与资源关联的客户端和服务指定的元数据。定义的值为：

* 符合 Astra 元数据架构如果在创建时未指定，则将创建没有标签的元数据对象。如果在更新时未指定，则元数据对象的标签、creationTimestamp 和 createdBy 将保留而不进行修改。


|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-user",
  "version": "1.2",
  "id": "5bad8e04-e2fd-5c43-98d7-300580993f49",
  "state": "pending",
  "isEnabled": "true",
  "authID": "HteLK3hk28sdbDLKHReB",
  "authProvider": "cloud-central",
  "firstName": "John",
  "lastName": "Doe",
  "email": "jdoe@example.com",
  "sendWelcomeEmail": "true",
  "lastActTimestamp": "2020-08-05T14:24:54.128427Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== 响应

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== 响应

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 



| invalidFields | 数组[link:#invalidFields["invalidFields"]] | False  a| 
无效请求正文字段列表

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== 响应

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 



| invalidFields | 数组[link:#invalidFields["invalidFields"]] | False  a| 
无效请求正文字段列表

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== 响应

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== 错误

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| 名称 | Type | Required | Description 


| type | string | True  a| 



| 标题 | string | True  a| 



| 详细信息 | string | True  a| 



| 状态 | string | True  a| 



| correlationID | string | False  a| 

|===
.错误响应示例
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== 定义

.查看定义
[%collapsible]
====
[role="api-collapsible-fifth-title"]
postalAddress

JSON 对象包含指定地址的字段集合。如果此 key 不存在，则表示未提供地址。如果此 key 存在，则所有六个包含的字段都将存在。如果用户未提供任何内容，则字符串将为空。

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| addressCountry | string | True  a| 
包含与邮政地址关联的国家/地区名称或国家/地区代码的 JSON 字符串，如 ISO 3166 Alpha-2 中所指定。定义的值为：

* 最小长度：2
* 最大长度：2




| addressLocality | string | True  a| 
包含与邮政地址关联的地点（例如城市）的 JSON 字符串。定义的值为：

* 最小长度：1
* 最大长度：63




| addressRegion | string | True  a| 
包含与邮政地址关联的区域（例如州）的 JSON 字符串。定义的值为：

* 最小长度：1
* 最大长度：63




| postalCode | string | True  a| 
包含与邮政地址关联的邮政编码的 JSON 字符串。定义的值为：

* 最小长度：1
* 最大长度：63




| streetAddress1 | string | True  a| 
包含与邮政地址关联的街道地址的 JSON 字符串。定义的值为：

* 最小长度：1
* 最大长度：63




| streetAddress2 | string | False  a| 
包含可选辅助街道地址信息、邮政信箱等的 JSON 字符串。定义的值为：

* 最小长度：1
* 最大长度：63


|===
[role="api-collapsible-fifth-title"]
类型 Astra 标签

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 



| value | string | True  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

与资源关联的客户端和服务指定的元数据。定义的值为：

* 符合 Astra 元数据架构如果在创建时未指定，则将创建没有标签的元数据对象。如果在更新时未指定，则元数据对象的标签、creationTimestamp 和 createdBy 将保留而不进行修改。


[cols="4*"]
|===
| 名称 | Type | Required | Description 


| labels | 数组[link:#type_astra_label["类型 Astra 标签"]] | False  a| 



| creationTimestamp | string | False  a| 



| modificationTimestamp | string | False  a| 



| 已创建 | string | False  a| 



| modifiedBy | string | False  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 
无效查询参数的名称



| 原因 | string | True  a| 
查询参数无效的原因

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| 名称 | Type | Required | Description 


| name | string | True  a| 
无效请求正文字段的名称



| 原因 | string | True  a| 
请求正文字段无效的原因

|===
====