---
sidebar: sidebar 
permalink: workflows/workflows_before.html 
keywords:  
summary:  
---
= 开始之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在管理 Astra 受管集群中的应用程序时使用这些工作流。


NOTE: NetApp 可以随时扩展和改进这些工作流，因此您应定期查看这些工作流。



== 一般准备

在使用任何 Astra 工作流之前，请务必查看 link:../get-started/prepare_to_use_workflows.html["准备使用这些工作流"]。



== 工作流类别

管理工作流按不同类别进行组织，以便更容易找到所需的工作流。

[cols="25,75"]
|===
| 类别 | Description 


| 应用程序控制 | 通过这些工作流，您可以控制受管应用程序和非受管应用程序。您可以列出应用程序以及创建和删除受管应用程序。 


| 应用程序保护 | 您可以使用这些工作流通过快照和备份保护受管应用程序。 


| 克隆和还原应用程序 | 这些工作流介绍了如何克隆和还原受管应用程序。 


| 支持 | 有多个工作流可用于调试和支持您的应用程序以及常规 Kubernetes 环境。 
|===


== 其他注意事项

使用管理工作流时，还需要注意一些其他注意事项。



=== 克隆应用程序

克隆应用程序时，需要考虑一些事项。以下所述参数是 JSON 输入的一部分。

源集群标识符:: 值 `sClusterID` 始终表示安装原始应用程序的集群。
集群标识符:: 值 `clusterID` 用于标识要安装新应用程序的集群。
+
--
* 在同一集群中克隆时， `clusterID` 和 `sClusterID` 具有相同的值。
* 在集群间克隆时，这两个值不同，并且 `clusterID` 应为目标集群的 ID 。


--
命名空间:: `namespace` 值必须与原始源应用程序不同。此外，克隆的命名空间不存在， Astra 将创建它。
备份和快照:: 您可以选择使用 `backupID` 或 `snapshotID` 参数从现有备份或快照克隆应用程序。如果不提供备份或快照，则 Astra 将首先创建应用程序的备份，然后从备份中克隆。




==== 还原应用程序

以下是还原应用程序时需要考虑的几个事项。

* 还原应用程序与克隆操作非常相似。
* 还原应用程序时，您必须提供备份或快照。

