---
sidebar: sidebar 
permalink: endpoints/resources.html 
keywords:  
summary:  
---
= 资源和端点
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用通过 Astra Control REST API 提供的资源来自动执行 Astra 部署。每个资源都通过一个或多个端点进行访问。本节介绍了可在规划自动化部署时使用的 REST 资源。


NOTE: 用于访问 Astra Control 资源的路径和完整 URL 的格式基于多个值。请参见 link:../rest-core/url_format.html["URL 格式"] 有关详细信息 ...另请参见  有关使用 Astra 资源和端点的详细信息。



== Astra Control REST 资源和端点

Astra Control REST API 中提供的主要资源端点分为三类。除了需要说明的情况外，可以使用一整套 CRUD 操作（创建，读取，更新，删除）来访问每个资源。



=== 核心资源

核心资源端点可提供建立和维护 Astra 运行时环境所需的基础服务。

ASUP:: ASUP 资源表示转发给 NetApp 支持部门的 AutoSupport 捆绑包。
凭据:: 凭据资源包含可用于 Astra 用户，集群，分段和存储后端的安全相关信息。
授权:: 授权资源表示根据活动许可证和订阅可供帐户使用的功能和容量。
事件:: 事件资源表示系统中发生的所有事件，包括归类为通知的子集。
功能:: 这些功能资源表示选定的 Astra 功能，您可以查询这些功能来确定它们是否已在系统中启用。访问权限仅限于只读。
许可证:: 许可证资源表示可用于 Astra 帐户的许可证。
通知:: 通知资源表示具有通知目标的 Astra 事件。访问权限按用户提供。
角色绑定:: 角色绑定资源表示特定用户对和帐户之间的关系。除了这两者之间的链接之外，还会通过特定角色为每个指定一组权限。
正在设置 ...:: 设置资源表示一组密钥值对，用于描述特定 Astra 帐户的功能。
订阅。:: 订阅资源表示 Astra 帐户的活动订阅。
令牌:: 令牌资源表示可通过编程方式访问 Astra Control REST API 的令牌。
未读通知:: 未读通知资源表示已分配给特定用户但尚未读取的通知。
用户:: 用户资源表示 Astra 用户能够根据其定义的角色访问系统。




=== 受管应用程序资源

通过受管应用程序资源端点，可以访问受管 Kubernetes 应用程序。

应用程序资产:: 应用程序资产资源表示管理 Astra 应用程序所需的内部状态信息集合。
应用程序备份:: 应用程序备份资源表示受管应用程序的备份。
应用程序快照:: 应用程序快照资源表示受管应用程序的快照。
受管应用程序:: 托管应用程序资源代表由 Astra 管理的 Kubernetes 应用程序。
计划:: 计划资源表示在数据保护策略中为受管应用程序计划的数据保护操作。




=== 拓扑资源

通过拓扑资源端点可以访问非受管应用程序和存储资源。

应用程序:: 应用程序资源表示所有 Kubernetes 应用程序，包括那些不受 Astra 管理的应用程序。
存储分段:: 存储分段资源表示用于存储由 Astra 管理的应用程序备份的 S3 云分段。
云:: 云资源表示 Astra 客户端为管理集群和应用程序而可以连接到的云。
集群:: 集群资源表示不受 Kubernetes 管理的 Kubernetes 集群。
受管集群:: 受管集群资源表示当前由 Kubernetes 管理的 Kubernetes 集群。
存储后端:: 存储后端资源表示可由 Astra 管理的集群和应用程序使用的存储服务提供商。
存储类:: 存储类资源表示已发现并可供特定受管集群使用的不同存储类或类型。
Volume:: 卷资源表示与受管应用程序关联的 Kubernetes 存储卷。




== 其他资源和端点

您可以使用多种其他资源和端点来支持 Astra 部署。


NOTE: 这些资源和端点当前未包含在 Astra Control REST API 参考文档中。

OpenAPI:: 通过 OpenAPI 端点可以访问当前的 OpenAPI JSON 文档和其他相关资源。
OpenMetrics:: 通过 OpenMetrics 端点，您可以通过 OpenMetrics 资源访问帐户指标。Astra 控制中心部署模式支持此功能。

