---
sidebar: sidebar 
permalink: get-started/prepare_to_use_workflows.html 
keywords: workflows, prepare workflows, use workflows 
summary: 在将 Astra 工作流用于实时部署之前，您应熟悉这些工作流的组织和格式。 
---
= 准备使用这些工作流
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在将 Astra 工作流用于实时部署之前，您应熟悉这些工作流的组织和格式。



== 简介

_Workflow _ 是完成特定管理任务或目标所需的一个或多个步骤的序列。Astra Control 工作流中的每个步骤均为以下步骤之一：

* REST API 调用（包含 curl 和 JSON 示例等详细信息）
* 调用另一个 Astra 工作流
* 其他相关任务（例如做出必要的设计决策）


这些工作流包括完成每个任务所需的核心步骤和参数。它们为自定义自动化环境提供了一个起点。


NOTE: 一个工作流只能包含一个步骤。这些单步工作流的格式与包含多个步骤的工作流略有不同。例如、删除显式步骤名称。操作或操作应根据工作流标题明确。



== 工作流类别

根据您的部署模式，有两大类 Astra 工作流可用。如果您使用的是 Astra 控制中心，则应先从基础架构工作流开始，然后再继续执行管理工作流。使用 Astra Control Service 时，通常可以直接转到管理工作流。


NOTE: 工作流中的cURL示例使用Astra Control Service的URL。在根据您的环境使用内部 Astra 控制中心时，您需要更改 URL 。



=== 基础架构工作流

这些工作流用于处理 Astra 基础架构，包括凭据，存储分段和存储后端。Astra 控制中心需要使用这些控制器，但在大多数情况下，也可以与 Astra 控制服务一起使用。这些工作流侧重于建立和维护 Astra 受管集群所需的任务。



=== 管理工作流

设置受管集群后、您可以使用这些工作流。管理工作流侧重于应用程序保护和支持操作、例如备份、还原和克隆应用程序。



== 通用输入参数

以下所述的输入参数对于用于说明 REST API 调用的所有 curl 示例通用。


NOTE: 由于这些输入参数是通用的要求，因此在各个工作流中不会对其进行进一步说明。如果在特定的 curl 示例中使用了其他输入参数，则会在 * 其他输入参数 * 一节中进行介绍。



=== 路径参数

每次 REST API 调用使用的端点路径都包括以下参数。另请参见 link:../rest-core/url_format.html["URL 格式"] 有关详细信息 ...

帐户 ID:: 这是用于标识运行 API 操作的 Astra 帐户的 UUIDv4 值。请参见 link:../get-started/get_api_token.html["获取 API 令牌"] 有关查找帐户 ID 的详细信息，请参见。




=== 请求标题

根据 REST API 调用，您可能需要包含多个请求标头。

Authorization:: 工作流中的所有 API 调用都需要 API 令牌来标识用户。您必须在 `Authorization` Request 标题中包含令牌。请参见 link:../get-started/get_api_token.html["获取 API 令牌"] 有关生成 API 令牌的详细信息。
内容类型:: 对于请求正文中包含 JSON 的 HTTP POST 和 PUT 请求，您应根据 Astra 资源声明介质类型。例如，在为受管应用程序创建快照时，可以包括标题 `Content-Type ： application/Astra-appsnap+json` 。
接受:: 您可以根据 Astra 资源声明响应中预期内容的特定介质类型。例如，在列出受管应用程序的备份时，您可以包括标题 `accept ： application/Astra-appBackup+json` 。但是，为了简单起见，工作流中的 curl 样本接受所有介质类型。




== 表示令牌和标识符

在 curl 示例中使用的 API 令牌和其他 ID 值是不透明的，没有明显的含义。因此，为了提高示例的可读性，不会使用实际令牌和 ID 值。而是使用较小的保留关键字，它具有以下几个优势：

* curl 和 JSON 示例更清晰，更易于理解。
* 由于所有关键字都使用相同的格式以及括号和大写字母，因此您可以快速确定要插入或提取的位置和内容。
* 不会丢失任何值，因为无法复制原始参数并将其用于实际部署。


这些变量经过格式设置、可在bash shell环境中使用。每个变量都以美元符号开头、并根据需要用双引号括起来。这使得他们可以被巴什所识别。名称始终使用大写。

以下是在 curl 示例中使用的一些常见保留关键字。此列表并非详尽无遗，我们会根据需要使用其他关键字。根据具体情况，其含义应该是显而易见的。

[cols="25,15,60"]
|===
| 关键字 | Type | Description 


| $account_ID | 路径 | 用于标识运行 API 操作的帐户的 UUIDv4 值。 


| $API_TOATHOR | 标题 | 标识和授权调用方的令牌。 


| $APP_ID | 路径 | 用于标识API调用的应用程序的UUIDv4值。 
|===


== 将示例与Bash结合使用

如果您直接使用工作流卷曲示例、则必须使用适合您环境的值更新其包含的变量。您可以手动编辑这些示例、也可以依靠bash shell为您执行替换、如下所述。


NOTE: 使用"Bash"的一个优点是、您可以在shell会话中设置一次变量值、而不是在每个CURL命令中设置一次。

.步骤
. 打开随Linux或类似操作系统提供的bash shell。
. 设置要运行的CURL示例中包含的变量值。例如：
+
`$API_TOKEN=SGgpXHeco6M8PLxzIlgbztA4k3_eX4UCa842hOXHBFA=`

. 从工作流页面复制卷曲示例并将其粘贴到shell终端中。
. 按*enter*执行以下任务：
+
.. 替换您设置的变量值。
.. 执行Curl命令。



